-- 코드를 입력하세요
SELECT b.PRODUCT_CODE, SUM(b.PRICE * a.SALES_AMOUNT) AS SALES
FROM PRODUCT b
JOIN OFFLINE_SALE a ON a.PRODUCT_ID=b.PRODUCT_ID
GROUP BY b.PRODUCT_CODE
ORDER BY SALES DESC, b.PRODUCT_CODE ASC