-- 코드를 입력하세요
-- 음식 종류별로 즐겨찾기가 가장 많은 곳 찾기
WITH rank_rest as(
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
DENSE_RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rank_fav
FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM rank_rest
where rank_fav = 1
order by FOOD_TYPE DESC

