-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE, 
    CASE
        when DATEDIFF(END_DATE, START_DATE) +1 >=30 then '장기 대여'
        else '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE >= '2022-09-01' and START_DATE < '2022-10-01'

ORDER BY HISTORY_ID DESC
   