-- 코드를 작성해주세요
-- 1, 2, 3/4, 5 6/7, 8, 9/10,11,12

SELECT CASE when MONTH(DIFFERENTIATION_DATE) >=1 and MONTH(DIFFERENTIATION_DATE) <=3 then '1Q'
when MONTH(DIFFERENTIATION_DATE) >= 4 and MONTH(DIFFERENTIATION_DATE)<=6 then '2Q'
when MONTH(DIFFERENTIATION_DATE) >= 7 and MONTH(DIFFERENTIATION_DATE) <=9 then '3Q'
when MONTH(DIFFERENTIATION_DATE) >= 10 and MONTH(DIFFERENTIATION_DATE)<=12 then '4Q' 
END as QUARTER,
COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER

