with JULY_G AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP  BY FLAVOR
)
SELECT j.FLAVOR
from JULY_G j
JOIN FIRST_HALF f ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
limit 3