-- 코드를 입력하세요
with base as(
    SELECT MEMBER_ID, MEMBER_NAME
from MEMBER_PROFILE p
where p.MEMBER_ID = (SELECT MEMBER_ID
from REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(REVIEW_ID) DESC
limit 1))

select MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
from base
JOIN REST_REVIEW r on r.MEMBER_ID = base.MEMBER_ID
order by r.REVIEW_DATE, r.REVIEW_TEXT
