-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
from BOOK
JOIN BOOK_SALES ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
where SALES_DATE >= '2022-01-01' and SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY